save_data: data/
src_vocab: data/vocab-en.txt
tgt_vocab: data/vocab-ro.txt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: data/train-en.txt
        path_tgt: data/train-ro.txt
        transforms: [sentencepiece]
    valid:
        path_src: data/valid-en.txt
        path_tgt: data/valid-ro.txt
        transforms: [sentencepiece]

src_subword_model: data/sentpiece_en_32k.model
tgt_subword_model: data/sentpiece_ro_32k.model

src_seq_length: 256
src_seq_length: 256

src_vocab: data/vocab-en.txt
tgt_vocab: data/vocab-ro.txt
src_vocab_size: 32000
tgt_vocab_size: 32000

save_model: models/model_wmt_en_ro
train_from: models/model_wmt_en_ro_step_70000.pt
save_checkpoint_steps: 5000
valid_steps: 5000
report_every: 100
seed: 42
train_steps: 200000
tensorboard: True
tensorboard_log_dir: tensorboard

# Batching
queue_size: 10000
bucket_size: 32768
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 2048
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: 0

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
position_encoding: true
